spring:
  datasource:
    url: jdbc:mysql://localhost/my_library?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Most_secure_root_password1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true # Showing log for each sql query

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect;

  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

server:
  port: 8080
